version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db-payment_provider
    environment:
      - POSTGRES_DB=payment_provider
      - POSTGRES_USER=eugene
      - POSTGRES_PASSWORD=eugene
    ports:
      - "5432:5432"


  server:
    build: .
    image: server-image
    container_name: server-container
    ports:
      - "8080:8080"
    depends_on:
      - db
